# Generated by Django 4.2.6 on 2023-10-09 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name Not Available', max_length=1000)),
                ('credits', models.CharField(default='Credits not available', max_length=1000)),
                ('title', models.CharField(default='Title not available', max_length=1000)),
                ('character_name', models.CharField(default='Character Name not available', max_length=1000)),
                ('img', models.TextField(default='https://westsiderc.org/wp-content/uploads/2019/08/Image-Not-Available.png')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title not available', max_length=1000)),
                ('media_type', models.CharField(default='Media type not available', max_length=1000)),
                ('year', models.IntegerField()),
                ('genre', models.CharField(default='Genre not available', max_length=1000)),
                ('duration', models.IntegerField()),
                ('disabilities', models.CharField(default='Disabilities not available', max_length=1000)),
                ('themes', models.CharField(max_length=1000)),
                ('img', models.TextField(default='https://westsiderc.org/wp-content/uploads/2019/08/Image-Not-Available.png')),
                ('description', models.TextField()),
                ('cast_members', models.ManyToManyField(to='criptastic.cast')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='No Title', max_length=1000)),
                ('reviewer_name', models.CharField(default='Anonymous', max_length=1000)),
                ('review_text', models.TextField(default='Review Text Not Available', max_length=1000)),
                ('date', models.CharField(default='No Date Added', max_length=1000)),
                ('casting_score', models.FloatField()),
                ('character_score', models.FloatField()),
                ('originality_score', models.FloatField()),
                ('accuracy_score', models.FloatField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='criptastic.movie')),
            ],
        ),
    ]
