# Generated by Django 4.2.6 on 2023-10-17 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criptastic', '0002_remove_review_reviewer_name_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='reviewer_name',
        ),
    ]
