# Generated by Django 4.2.6 on 2023-10-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criptastic', '0003_remove_review_reviewer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewer_name',
            field=models.CharField(default='Anonymous', max_length=1000),
        ),
    ]
